#!/usr/bin/env bash
# ThistleClient runner
DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
export PYTHONPATH="$DIR:$PYTHONPATH"

exec /usr/bin/python3 "$DIR/thistle_client/main.py" "$@"
